
USE [master]
GO

/****** Object:  Database [EKART_DEV]    Script Date: 8/19/2023 12:04:45 PM ******/
CREATE DATABASE [EKART_DEV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EKART_DEV', FILENAME = N'C:\Users\Jolin Abrahm\EKART_DEV.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EKART_DEV_log', FILENAME = N'C:\Users\Jolin Abrahm\EKART_DEV_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

ALTER DATABASE [EKART_DEV] SET COMPATIBILITY_LEVEL = 150
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EKART_DEV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EKART_DEV] SET ANSI_NULL_DEFAULT ON
GO

ALTER DATABASE [EKART_DEV] SET ANSI_NULLS ON
GO

ALTER DATABASE [EKART_DEV] SET ANSI_PADDING ON
GO

ALTER DATABASE [EKART_DEV] SET ANSI_WARNINGS ON
GO

ALTER DATABASE [EKART_DEV] SET ARITHABORT ON
GO

ALTER DATABASE [EKART_DEV] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [EKART_DEV] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [EKART_DEV] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [EKART_DEV] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [EKART_DEV] SET CURSOR_DEFAULT  LOCAL
GO

ALTER DATABASE [EKART_DEV] SET CONCAT_NULL_YIELDS_NULL ON
GO

ALTER DATABASE [EKART_DEV] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [EKART_DEV] SET QUOTED_IDENTIFIER ON
GO

ALTER DATABASE [EKART_DEV] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [EKART_DEV] SET  DISABLE_BROKER
GO

ALTER DATABASE [EKART_DEV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [EKART_DEV] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [EKART_DEV] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [EKART_DEV] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [EKART_DEV] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [EKART_DEV] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [EKART_DEV] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [EKART_DEV] SET RECOVERY SIMPLE
GO

ALTER DATABASE [EKART_DEV] SET  MULTI_USER
GO

ALTER DATABASE [EKART_DEV] SET PAGE_VERIFY NONE
GO

ALTER DATABASE [EKART_DEV] SET DB_CHAINING OFF
GO

ALTER DATABASE [EKART_DEV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [EKART_DEV] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [EKART_DEV] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [EKART_DEV] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [EKART_DEV] SET QUERY_STORE = OFF
GO

USE [EKART_DEV]
GO

/****** Object:  Table [dbo].[EkartCartItem]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartLoopUpRoles]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartOrderDetails]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartOrderItem]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartPaymentDetails]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartProductCategory]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartProductDiscount]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartProductInventory]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartProducts]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartShoppingSession]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartTokenDetails]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartUserAddress]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartUserDetail]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartUserInRoles]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EkartUserPayment]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[usp_Ekart_Authorize_User]    Script Date: 8/19/2023 12:04:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [EKART_DEV] SET  READ_WRITE
GO
