CREATE TABLE [dbo].[EkartUserInRoles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EkartUserInRoles]  WITH CHECK ADD FOREIGN KEY([RoleId])
REFERENCES [dbo].[EkartLoopUpRoles] ([Id])
GO
ALTER TABLE [dbo].[EkartUserInRoles]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[EkartUserDetail] ([Id])